### ISSUE TITLE
Please add Pin1 marker for U1 and U3

### ISSUE THREAD

**Issue by phako** [SukkoPera/OpenFlops#10]
Not strictly necessary, but would improve convenience :)

**Comment by SukkoPera** [comment]
The marker is already there. The silkscreen has a longer line on the pin 1 side. I agree it's pretty hard to see, but it's the way KiCad footprints are designed and I don't want to modify them just for this. Ask them to make their footprints clearer :).

**Comment by phako** [comment]
Ohhh, right. Totally didn't get that, was looking for the dot :) Nevermind then
