### ISSUE TITLE
Idea: add 26pin connector version

### ISSUE THREAD

**Issue by crazycusti** [SukkoPera/OpenFlops#11]
hi!

this board would be awesome for my old 486 notebook :) 

but it had an 26pin slim connector (like citizen w1d floppydrives)

i had no skills to change the gerberfiles. :(

**Comment by SukkoPera** [comment]
This is a very good idea, but I'm not going to do it. Hopefully someone will help, tagging as *help wanted*.

**Comment by cyberluke** [comment]
I would do it if I know how to learn to do it. Any ideas where to learn what kind of connector is required? For example PCD-4ND and PCD-5ND have floppy in some kind of boxed module and the connector outside is not a standard 26pin FPC. Then some use 1.0mm FPC, some use 0.5mm FPC. That would be still okay, you can find the pinout. But someone would need to recommend what software to use to modify the gerberfiles and where to get all these connectors from old 486 laptops (not just FPC).

**Comment by SukkoPera** [comment]
You don't want to modify the Gerber files, LOL. This really says it all why people do not understand how much added value an open source project is, wrt those that are just "free gerbers", sigh.

What you want to do is use [KiCad](https://www.kicad.org) (this project currently uses KiCad 5) to update the schematics and the PCB and - only then - regenerate the gerbers for production.

[This](https://docs.kicad.org/6.0/en/getting_started_in_kicad/getting_started_in_kicad.html) happens to be a good KiCad Tutorial, it's an updated versione of the same one I used a few years ago to get started.

I can't help with the different connectors, unfortunately, never seen one of those drives.

**Comment by bschwand** [comment]
you can buy an fpc 26 to 34 pin header for a few bucks on aliexpress

**Comment by SukkoPera** [comment]
Sigh.

**Comment by csulaguy** [comment]
After some googling, I ended up here for the same reason as the OP. Unfortunately, I also don't know the first thing about designing a circuit board. In regards to @bschwand , I'm sure you could do an adapter, but why? I think having a **native** 26 pin version makes more sense for those of us who use laptop-style drives. I know there are musical instruments and industrial control devices that also use the same laptop-style drives.

**Comment by SukkoPera** [comment]
That's exactly the point of open source stuff: you can see how it's made and modify it to suit your needs, rather than being just a way to make a quick buck as seems to be the common understanding in the retrocomputing community.

It actually *thrives* when many people do so, so just pick the tutorial and do it, it's an excellent task for learning some basics that will surely turn out useful in the future.

**Comment by mpictor** [comment]
This would be helpful to me as well. Can't promise anything but I will try to find time to do it.

I'm hoping it's possible to fit both footprints on the PCB so it can be used either way (depending on which is populated).

**Comment by SukkoPera** [comment]
I think this has now been done: https://github.com/silvervest/OpenFlops-W1D.
