### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by sur1v** [SukkoPera/OpenFlops#12]
I just wanted to thanks for open-source this hardware and code.

I'm currently porting a old Nintendo Super Famicom (SNES) copier (Doctor SF 3) that holds a floppy drive to OpenFlops.

Will create content documenting the process soon. Thanks again!

**Comment by SukkoPera** [comment]
You are welcome, that would definitely be a great read! :)

**Comment by wasauce** [comment]
This project is awesome.

**Comment by SukkoPera** [comment]
Thanks, unfortunately it seems nobody is interested in bringing it further.

**Comment by SukkoPera** [comment]
No news in 3+ years, I guess we can close this :(.
