### ISSUE TITLE
First PCB assembly

### ISSUE THREAD

**Issue by dippaolo** [SukkoPera/OpenFlops#14]
PCB ordered from PCBWAY from the link:
https://www.pcbway.com/project/shareproject/OpenFlops_V1.html

I got 1 piece of STM microcontroller.

I soldered by dragging the soldering iron over the legs.
I checked under the microscope.
I soldered Y1, C3, C5, BOOT0, TX, RX.
Programmed microprocessor - successful :)

In the next step I want to solder P7. Is it enough to see the inscription on OLED FlashFloppy?

**Comment by SukkoPera** [comment]
I think so, you might also need R3 and R4 depending on your particular OLED screen.
