### ISSUE TITLE
How to connect OpenFlops for IBM 3174?

### ISSUE THREAD

**Issue by blackbit42** [SukkoPera/OpenFlops#15]
Hi

The FlashFloppy documentation has instructions to install a diode between two pins for operation in an IBM 3174 controller.
That documentation is focused on the original GoTek hardware.
Pin header layout and designations on the OpenFlops are different.
Can you please advise which pins on the OpenFlops are equivalent to [this](https://github.com/keirf/FlashFloppy/wiki/Host-Platforms#ibm-3174) so I can install that diode correctly.

**Comment by SukkoPera** [comment]
I **think** it goes like this:

![image](https://user-images.githubusercontent.com/1316870/125501048-7d3bead5-a286-48e3-928c-817b9aede787.png)

And put a jumper between 0 and SEL1.

**No guarantees!**

**Comment by blackbit42** [comment]
Works like a charm. Thanks!
