### ISSUE TITLE
Where is the BOM?

### ISSUE THREAD

**Issue by bjstigall** [SukkoPera/OpenFlops#16]
I can't find the Bill of Materials.

**Comment by SukkoPera** [comment]
Just open your eyes.

**Comment by bjstigall** [comment]
Very professional, thanks.

Sent from Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by bjstigall** [comment]
Thanks for the help.

Sent from Outlook<https://aka.ms/qtex0l> for iOS
________________________________
