### ISSUE TITLE
Problems working on ThinkPad 755C

### ISSUE THREAD

**Issue by csulaguy** [SukkoPera/OpenFlops#19]
The original drive is a Teac FD-05HG. I can install OS/2 for instance, but if I try to use IBM's self extracting disk imaging tools (Sydex I believe) or rawrite2 for Linux, it fails and reports the sector isn't found.
I've made some progress perusing through github, but it seems utilities that access the drive in a certain way fail. Not sure if there are specific settings I need to make in ff.cfg or if there are modifications that need to be done to the board.

The ThinkPad GUI utility also reports no 3.5" drive is installed, even though I can still access it for most things and install things (just having problems with what I presume is software speaking directly to hardware).

**Comment by SukkoPera** [comment]
I think that should raise this on [FlashFloppy's page](https://github.com/keirf/FlashFloppy).
