### ISSUE TITLE
Cannot load file from USB

### ISSUE THREAD

**Issue by Vanles** [SukkoPera/OpenFlops#25]
I soldered three boards. FlashFloppy works, the display turns on and shows the contents. When the Amiga starts, it tries to load from the USB, but nothing happens. Has anyone had this problem and knows which component I should look for?

Loading the company software via the USB also works. So it could have something to do with the connection on the floppy disk.

All three boards have the same problem.

Thanks
Marco

**Comment by SukkoPera** [comment]
Did you put a jumper between SEL0 and 0? Also try putting/removing one on JC and/or configure FlashFloppy to Shugart mode explicitly from its settings file.

**Comment by Vanles** [comment]
I found the problem. A dealer sent me a bad chip. Not the 74HCT04 but the 74HCT02. After replacing it, the drives work.

**Comment by SukkoPera** [comment]
Well, that is certainly interesting! Glad you found the issue :).
