### ISSUE TITLE
Strange issue on openflops hardware with FlashFloppy

### ISSUE THREAD

**Issue by ixmeins** [SukkoPera/OpenFlops#5]
I've built up several Openflops boards and flashed them with Flashfloppy 3.16 (and tried older versions). One out of 5 boards will successfully work with any Amstrad disk image files (DSK or HFE) whereas the others all return read errors from the OS when trying to use DSK files. I have compared the boards and can't see any differences. Waveforms on read, index etc all look very similar on the scope. These same "faulty" boards will work with HXC firmware. Has anyone else experienced this type of behaviour on the openflops hardware?

**Comment by simulant-systems** [comment]
Hi I just wanted to reply here as I noticed on the FlashFloppy issues section that this has been fixed by doing a RESET holding both buttons :)

**Comment by SukkoPera** [comment]
Thanks @simulant-systems. @ixmeins Can you please confirm?

**Comment by SukkoPera** [comment]
I'm closing this even if we got no reply. I assume no more comments means everything's working fine.
