### ISSUE TITLE
Crashes my A2000

### ISSUE THREAD

**Issue by SmoothAdmin** [SukkoPera/OpenFlops#8]
After putting the correct files on my 16GB USB thumb drive and booting from it, anytime I add ADF files to the entry points 001 extra and press F10 the system crashes. The only thing that works is so soft reboot the A2000. If I select an ADF and press F7 that works. So its only creating a custom list and pressing F10 to save and reboot?

I using the Simulant drive with FW 3.22.

This is the drive:
https://www.simulant.uk/shop/Floppy-Disk-Drive-USB-Emulator-OpenFlops-FlashFloppy-%20Gotek-upgrade?manufacturer_id=12

**Comment by SukkoPera** [comment]
I think you'd better raise this issue against FlashFloppy. I've never used the "entry points" myself, life is so much better with an OLED and direct directory navigation :).

**Comment by SukkoPera** [comment]
Closing because of lack of feedback.
