### ISSUE TITLE
Can STM32F106RBT6 used?

### ISSUE THREAD

**Issue by tfhh** [SukkoPera/OpenFlops#9]
Hi,

the MPU "STM32F105RBT6" isn´t easy to get here, but the STM32F10**6**RBT6 is good availible. Is it possible to use the STM32F106RBT6 instead of STM32F105RBT6?

Thanks!

**Comment by SukkoPera** [comment]
No idea. Actually I can find no mention of the F106 line [on the STM32 product page](https://www.st.com/en/microcontrollers-microprocessors/stm32f1-series.html).

**Comment by tfhh** [comment]
Hi, thanks for your fast answer. I´ve found some in Poland, so I close this now.
